--CRIANDO TABELA
CREATE TABLE PRODUTOS(

	CODIGO			INT			NOT NULL,
	DESCRICAO		VARCHAR(50) NOT NULL,
	DATA_VALIDADE	DATETIME,
	EAN				VARCHAR(15)	NOT NULL,
	IND_INATIVO		INT			NOT NULL DEFAULT 0
)

--ADICIONANDO CODIGO DA TB PRODUTOS COMO PRIMARY KEY
ALTER TABLE PRODUTOS 
	ADD CONSTRAINT PK_PRODUTOS 
		PRIMARY KEY(CODIGO);

--CRIANDO INDEX DE AUTOINCREMENTO PARA CODIGO DA TB PRODUTOS
CREATE INDEX IDX_PRODUTOS_EAN
	ON PRODUTOS(EAN);

--INSERINDO DADOS NA TB PRODUTOS
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DATA_VALIDADE, EAN, IND_INATIVO) VALUES (1, 'Nome do Produto', GETDATE(), '1920391929', 0);
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, EAN) VALUES (2, 'Nome do Produto2', '1920391929');

--IMPLEMENTANDO FUNCIONALIDADES
SELECT COUNT(*) AS TOTAL_REGISTROS 
					FROM PRODUTOS

					
CREATE TABLE LOJAS(

	CODIGO			INT,
	NOME			VARCHAR(50) NOT NULL,
	IND_INATIVO		INT			NOT NULL DEFAULT 0
	CONSTRAINT PK_LOJAS PRIMARY KEY(CODIGO)
);


--POPULANDO TB LOJA
INSERT INTO LOJAS(CODIGO, NOME) VALUES (1000, 'Filial Conjunto Muribeca'), (1001, 'Filial Recife'), (1002, 'Filial Igarassu');

CREATE TABLE ESTOQUES(
	
	CODIGO_PRODUTO	INT	NOT NULL,
	CODIGO_FILIAL	INT	NOT NULL,
	QUANTIDADE		DECIMAL NOT NULL DEFAULT 0,
	CONSTRAINT PK_ESTOQUE PRIMARY KEY(CODIGO_PRODUTO, CODIGO_FILIAL)
);

ALTER TABLE ESTOQUES 
	ADD CONSTRAINT FK_ESTOQUES_PRODUTOS 
		FOREIGN KEY (CODIGO_PRODUTO)
		REFERENCES PRODUTOS(CODIGO);

ALTER TABLE ESTOQUES
	ADD CONSTRAINT FK_ESTOQUES_LOJAS 
		FOREIGN KEY (CODIGO_FILIAL)
		REFERENCES LOJAS(CODIGO);

--PARA EXCLUIR UMA CONSTRAINT CRIADA: 
--ALTER TABLE NOME_TABELA DROP CONSTRAINT NOME_DA_CONSTRAINT

--BUSCA RELACIONANDO TABELAS
SELECT E.CODIGO_FILIAL,
	L.NOME 
	FROM ESTOQUES E INNER JOIN LOJAS L 
	ON E.CODIGO_FILIAL = L.CODIGO; 
			
